services:
  - type: web
    name: student-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://hsanmiguel_db_user:hanssanmiguel22@cluster0.hh3eumt.mongodb.net/student_db?retryWrites=true&w=majority
    autoDeploy: true